#!/usr/bin/env ruby

require 'json'
require_relative 'scrub_json.rb'

sensitive_fields = File.open(ARGV[0]).readlines.map(&:strip)
input_json = JSON.parse(File.open(ARGV[1]).read)

scrubber = ScrubJson.new(sensitive_fields, input_json)

scrubber.declare
